FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/echo/ .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o echo-server ./main.go

FROM alpine:3.18
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/echo-server .
EXPOSE 8081
CMD ["./echo-server"]
